In [42]:
import gensim

text = []
with open("train.csv", encoding='utf-8') as file:
    line = file.readline()
    while line:
        if int(line[0]) == 1 :
            text.append(gensim.utils.simple_preprocess(line[2:]))
        line = file.readline()

model = gensim.models.Word2Vec (text, size=10, window=10, min_count=2, workers=4)
model.train(text, total_examples=len(text), epochs=500)

(463323407, 557168000)

In [49]:
key_world = ['president','nuclear','people','government']

In [63]:
import numpy as np
v = []
for i in range(len(key_world)):
    temp = model.wv[key_world[i]]
    v.append(temp / np.linalg.norm(temp))
    
v = np.array(v).T
print(v)

[[-0.07365    -0.24891973 -0.26054537 -0.2534251 ]
 [ 0.2848378  -0.35679132 -0.22315472  0.21876787]
 [ 0.36890674  0.25959757 -0.3470516   0.10189264]
 [-0.5877324   0.06722361 -0.0142916   0.06183667]
 [ 0.14802533 -0.1572865  -0.5122748   0.1927355 ]
 [ 0.1342263   0.01636912 -0.076187    0.25077948]
 [ 0.07447902  0.29708406 -0.63017094 -0.16462053]
 [-0.2565427  -0.6545122   0.21923795 -0.8574811 ]
 [-0.56430846  0.4426831  -0.13541691 -0.03175185]
 [ 0.04677713 -0.0347633   0.1729758   0.10144518]]


In [64]:
word = 'government'
w = np.array(model.wv[word])
w = w / np.linalg.norm(w)

# np.linalg.norm(np.dot(np.dot(v, np.dot(np.linalg.inv(np.dot(v.T, v)), v.T)), w.T))
sum = 0 
for i in range(len(key_world)):
    sum += np.exp(abs(np.dot(w,v[:,i])))
print(np.log(sum/4))

0.5619460646465471


0.15075526538256456
